name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - QAT
          - UAT
          - DEV

jobs:
  playwright-test:
    runs-on: ubuntu-latest

    env:
      APP_ENV: ${{ github.event.inputs.environment }}

      # QAT secrets
      BASE_URL: ${{ secrets.BASE_URL }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      # UAT secrets
      UAT_BASE_URL: ${{ secrets.UAT_BASE_URL }}
      UAT_ADMIN_USERNAME: ${{ secrets.UAT_ADMIN_USERNAME }}
      UAT_ADMIN_PASSWORD: ${{ secrets.UAT_ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report